Mode = "debug"
ApiListen = ":5566"
DatabaseURL = "user01:sql001@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local"
SecretKey = "test"

[Statistic]
    Disable = false
    Crontab = "0 */5 * * * *"

[Email]
    Name = "titan"
    SMTPHost = "smtp.qq.com"
    SMTPPort = "587"
    Username = "titan@gmail.com"
    Password = "test"


